exp: ddpm
eval: True
id: single_mod
data: CITYSCAPES_RGB
data_folder: data
batch_size: 16
future_frames: 28  # Future frames to predict

ae_config: configs/autoencoder/8x128x128.yaml
ae_model: checkpoints/ae_rgb_8f_cityscapes.pth
ae_cond_config: configs/autoencoder/2x128x128.yaml
ae_cond_model: checkpoints/ae_rgb_2f_cityscapes.pth

diffusion_config: configs/diffusion/128x128.yaml
diffusion_model: results/ddpm_single_mod_CITYSCAPES_RGB_42/ema_model_0.pth # e.g.
