model:
  resume: False
  amp: True
  base_learning_rate: 1.0e-4
  max_iter: 1000000
  log_freq: 1000
  eval_freq: 10000
  eval_samples: 4
  params:
    embed_dim: 4
    perceptual_weight: 4.0
    lossconfig:
      params:
        disc_start: 100000000

    ddconfig:
      channels: 192
      resolution: 128  # For non-square images set a tuple [h, w] (e.g. resolution: [128, 256])
      frames: 2
      in_channels: 3
      out_channels: 3
      splits: 1
